name: meg_m2_rnaseq_bash_2024
# Updated environment for 2024 mouse RNA-seq course

channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Jupyter dependencies (keeping same versions as they worked well)
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  - jupyter-archive

  # Bash environment
  - python>=3.8
  - pip
  - pip:
    - bash_kernel

  # RNA-seq analysis tools (with versions from our analysis)
  - fastqc
  - fastp=0.23.1
  - star=2.7.11a
  - samtools=1.18
  - multiqc=1.13
  - fastq-screen=0.15.3
  - qualimap=2.2.2b
  - subread=2.0.6  # for featureCounts
  - salmon  # for transcript quantification

  # Additional tools from old environment that might be useful
  - bedtools
  - htseq
